(let* ((name "cl-i"))
  (handler-bind ((uiop/lisp-build:compile-file-error (lambda (condt) (declare (ignore condt)) (invoke-restart (find-restart 'accept)))))
    (handler-bind ((asdf/find-component:missing-component (lambda (condt)
                                                            (declare (ignore condt))
                                                            (invoke-restart (find-restart 'continue)))))
      (handler-bind ((error (lambda (condt)
                              (declare (ignore condt))
                              (invoke-restart (find-restart 'continue)))))
  (asdf:load-system name)
  (asdf:load-system (format nil "~A-tests" name))))))