name: Deploy Docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs
  cancel-in-progress: false

jobs:
  docs:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Check out OCICL
        uses: actions/checkout@v4
        with:
          repository: ocicl/ocicl
          path: ocicl

      - name: Install build dependencies
        run: |
          set -ex
          sudo apt-get install -y jq
          download_url=$(curl -s https://api.github.com/repos/roswell/roswell/releases/latest | \
            jq -r '.assets |
                   .[] |
                   select(.name|test("\\.deb$")) |
                   .browser_download_url')
          curl -L "${download_url}" --output roswell.deb
          sudo apt-get install -y ./roswell.deb make
          ros install sbcl-bin
          ros use sbcl-bin
          sbcl_vers=$(ls -1A ~/.roswell/impls/x86-64/linux/sbcl-bin)
          export PATH=~/.roswell/impls/x86-64/linux/sbcl-bin/${sbcl_vers}/bin:${PATH}
          cd ocicl
          mkdir -p ~/.local/bin/
          sbcl --load setup.lisp
          chmod a+x ocicl
          mv ocicl ~/.local/bin
          cat >> ~/.roswell/init.lisp << ROSWELL
          #-ocicl
          (when (probe-file #P"~/.local/share/ocicl/ocicl-runtime.lisp")
            (load #P"~/.local/share/ocicl/ocicl-runtime.lisp"))
          (asdf:initialize-source-registry
            (list :source-registry (list :directory (uiop:getcwd)) :inherit-configuration))
          ROSWELL

      - name: Make the docs
        run: |
          sbcl_vers=$(ls -1A ~/.roswell/impls/x86-64/linux/sbcl-bin)
          export PATH=~/.roswell/impls/x86-64/linux/sbcl-bin/${sbcl_vers}/bin:~/.local/bin:${PATH}
          make docs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload docs
          path: 'docs/build/cliff-command-line-interface-functional-framework/html/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4