name: Deploy Docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs
  cancel-in-progress: false

jobs:
  docs:
    name: Make the docs
    runs-on: ubuntu-latest
    container:
      image: djhaskin987/roswell-sbcl-ocicl:latest
      options: --cpus 1 --user root
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Restore cache
        id: cache-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.roswell
            ~/.cache/common-lisp
          key: ${{ runner.os }}

      - name: Restore systems
        id: cache-systems
        uses: actions/cache@v3
        with:
          path: |
            systems/
          key: ${{ hashFiles('systems.csv') }}

      - name: Make the docs
        run: |
          chown -R builder: .
          chmod ugo+rwX -R .
          su builder << BUILDER
          ocicl install
          make docs
          BUILDER

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload docs
          path: 'docs/build/cliff-command-line-interface-functional-framework/html/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4